sudo: false # use docker
dist: trusty

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install: 
  - pip3 install -e .
  - pip3 install pytest flake8
  
script: 
  # - make flake8
  - make ci
  
notifications:
  email:
    - dpark.ci@gmail.com
  slack: vcrs:EwEGGxeJTXj75vTJuc4sLQ4S